version: '3'

services:
  # Application
  app:
    # Path Dockerfile
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: cursonestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  # Database
  db:
    build: .docker/postgres
    container_name: cursonestjs-db
    restart: always
    # Terminal
    tty: true
    ports:
    - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cursonestjs

        # Database
  dbtest:
    build: .docker/postgres
    container_name: cursonestjs-dbtest
    restart: always
    # Terminal
    tty: true
    ports:
    - "5433:5432"
    volumes:
      - .docker/dbdatatest:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testedb

  pgadmin:
    image: dpage/pgadmin4
    container_name: cursonestjs-pgamin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
